version: "3.9"
services:
  backend:
    container_name: ecommerce-rest-api
    hostname: ecommerce-rest-api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - DOCKER_BUILDKIT=1
    entrypoint: ["sh", "-c", "sleep 5 && java -jar app.jar --spring.profiles.active=mail-gmail,db-psql-variables,test,load-data"]
    ports:
      - "7937:8080"
    restart: on-failure
    environment:
      - PSQL_HOSTNAME=ecommerce-db
      - PSQL_PORT=5432
      - PSQL_DB_NAME=staging
      - PSQL_USER=cris6h16
      - PSQL_PASS=12345678
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - PSQL_SCHEMA=public
    networks:
      - private
      - public
#    volumes:
#      - maven-cache:/root/.m2
    depends_on:
      - db

  db:
    container_name: ecommerce-db
    hostname: ecommerce-db
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_USER: cris6h16
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: staging
    networks:
      - private

networks:
  private:
  public:

#volumes:
#  maven-cache:
#    driver: local
