package org.cris6h16.facades.Exceptions;

public enum ApplicationErrorCode {
    PAGE_SIZE_TOO_BIG,
    INVALID_CREDENTIALS,
    EMAIL_NOT_VERIFIED,
    VALID_VERIFICATION_CODE_NOT_FOUND,
    FORBIDDEN_SORT_PROPERTY,
    ENABLED_USER_NOT_FOUND,

    USER_NOT_FOUND_BY_ID,
    CART_ITEM_NOT_FOUND,
    UNSUPPORTED_ACTION_TYPE,
    PRODUCT_NOT_FOUND_BY_ID
}
