package org.cris6h16.facades.Exceptions;

public enum ApplicationErrorCode {
    INVALID_CREDENTIALS,
    EMAIL_NOT_VERIFIED,
    VALID_VERIFICATION_CODE_NOT_FOUND,
    USER_NOT_FOUND_BY_ID,
    ENABLED_USER_NOT_FOUND_BY_ID,
    CART_ITEM_NOT_FOUND, PRODUCT_NOT_FOUND_BY_ID
}
