package org.cris6h16.file.Exceptions;

public enum FileErrorCode {
    FILE_DELETE_BY_URL_ERROR,
    FILE_UPLOAD_ERROR,
    FILE_UPLOAD_ALL_RETRIES_ERROR,
    EMPTY_MULTIPART_FILE,
    FILE_SIZE_EXCEEDED,
    FILE_CONTENT_TYPE_IS_NOT_IMAGE,
    INVALID_FILE_NAME,
    FILE_DELETE_BY_URL_ALL_RETRIES_ERROR,
    EMPTY_FILE_LIST,
    INVALID_CONTENT_TYPE,
}
