package org.cris6h16.file.Exceptions;

public enum FileErrorCode {
    FILE_DELETE_BY_URL_ERROR,
    FILE_UPLOAD_ERROR,
    FILE_UPLOAD_ALL_RETRIES_ERROR,
    FILE_IS_EMPTY,
    FILE_SIZE_EXCEEDED,
    FILE_CONTENT_TYPE_IS_NOT_IMAGE,
    FILE_CONTENT_TYPE_IS_NULL,
    FILE_DELETE_BY_URL_ALL_RETRIES_ERROR,
    FILE_LIST_IS_EMPTY,
}
