package org.cris6h16.cart;

public enum CartComponentErrorCode {
    PRODUCT_NOT_FOUND_BY_ID,
    USER_NOT_FOUND,
    INVALID_USER_ID
    , NULL_QUANTITY,
    QUANTITY_LESS_THAN_ONE,
    NULL_PRODUCT_ID,
    PRODUCT_ID_LESS_THAN_ONE,
    INVALID_PRODUCT_ID,
    INVALID_QUANTITY,
    NULL_USER_ID,
    USER_ID_LESS_THAN_ONE,
    NULL_CART_ITEM_ID,
    CART_ITEM_ID_LESS_THAN_ONE,
    CART_ITEM_NOT_FOUND_BY_ID,
    USER_NOT_FOUND_BY_ID
}
