package org.cris6h16.user.Exceptions;

public enum UserErrorCode {
    EMAIL_TOO_LONG,
    EMAIL_REGEX_MISMATCH,
    USER_ID_LESS_THAN_1,
    USER_NOT_FOUND,
    INVALID_BALANCE,
    EMAIL_ALREADY_EXISTS,
    FIRSTNAME_LENGTH_MISMATCH,
    LASTNAME_LENGTH_MISMATCH,
    PASSWORD_LENGTH_MISMATCH,
}
