package org.cris6h16.Exception;

public enum AddressErrorCode {
    INVALID_COUNTRY,
    INVALID_STATE,
    INVALID_MOBILE_NUMBER,
    INVALID_CITY, COUNTRY_NOT_FOUND, ADDRESS_NOT_FOUND, INVALID_STREET, INVALID_REFERENCE,
}
