package org.cris6h16.product.Exceptions;


public enum ProductErrorCode {
    USER_ID_NULL,
    CATEGORY_ID_NULL,
    IMAGE_URL_NULL,
    IMAGE_URL_TOO_LONG,
    USER_ID_LESS_THAN_ONE,
    CATEGORY_ID_LESS_THAN_ONE,
    APPROX_WEIGHT_LB_NULL,
    STOCK_NEGATIVE,
    APPROX_HEIGHT_CM_NULL,
    APPROX_HEIGHT_CM_NEGATIVE,
    APPROX_WIDTH_CM_NULL,
    APPROX_WIDTH_CM_NEGATIVE,
    APPROX_WEIGHT_LB_NEGATIVE,
    DESCRIPTION_NULL,
    DESCRIPTION_TOO_LONG,
    STOCK_NULL,
    PRICE_NULL,
    PRICE_NEGATIVE,
    PRODUCT_NAME_NULL,
    PRODUCT_NAME_TOO_LONG,
    CATEGORY_NAME_TOO_LONG,
    PRODUCT_ID_NULL,
    PRODUCT_ID_LESS_THAN_ONE,
    UNIQUE_USER_ID_PRODUCT_NAME,
    CATEGORY_NAME_NULL,
    CATEGORY_NOT_FOUND_BY_ID,
    USER_NOT_FOUND_BY_ID, PRODUCT_NOT_FOUND_BY_ID;

}