package org.cris6h16.product.Exceptions;


public enum ProductErrorCode {
    WEIGHT_POUNDS_NEGATIVE,
    WIDTH_CM_NEGATIVE,
    STOCK_NEGATIVE,
    HEIGHT_CM_NEGATIVE, // todo: borrar codigo muertol
    CATEGORY_ID_NEGATIVE,
    UNSUPPORTED_FILTER_ATTRIBUTE,
    USER_ID_NEGATIVE,
    LENGTH_CM_NEGATIVE,
    PRODUCT_HAS_NO_IMAGES,
    IMAGE_URL_TOO_LONG,
    PRICE_FILTER_INVALID_FORMAT,
    INVALID_CATEGORY_ID,
    PRODUCT_NAME_LENGTH_MISMATCH,
    INVALID_STOCK,
    INVALID_PRICE,
    PRODUCT_DESCRIPTION_LENGTH_MISMATCH,
    CATEGORY_NAME_TOO_LONG,
    PRODUCT_ID_INVALID,
    UNIQUE_USER_ID_PRODUCT_NAME,

    CATEGORY_NOT_FOUND_BY_ID,
    USER_NOT_FOUND_BY_ID,
    PRODUCT_NOT_FOUND_BY_ID,
    PRICE_FILTER_ERROR_PARSING_STR_TO_BIGDECIMAL
}