package org.cris6h16.email.Exceptions;

public enum EmailErrorCode {
    EMAIL_TOO_LONG,
    EMAIL_REGEX_MISMATCH,
    CODE_NULL,
    CODE_IS_BLANK,
    CODE_INVALID_LENGTH,
    ACTION_TYPE_NULL,
    ACTION_TYPE_TOO_LONG,
    EMAIL_NULL,
    ACTION_TYPE_BLANK,
    EMAIL_SENDING_MAX_RETRIES_ERROR;

}
